name: pipeline CI
on:
  push:
    branches:
      - main
      - master
run-name: primeira pipeline teste NP
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout - clone
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Compilation
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: -3
          format: 'mm.ss'

      - name: Usage Time
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME 

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pipeline:${{ steps.time.outputs.time }}


